dist: trusty
sudo: required
notifications:
  email: false
language:
  - cpp
compiler:
  - gcc
  # - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      #- gcc-7
      - g++-7
      - lcov
      - curl
script:
  #- export CC=gcc-7
  - export CXX=g++-7

script:
  - export OMP_NUM_THREADS=1
  - mkdir Debug
  - cd Debug
  - cmake -DCMAKE_BUILD_TYPE=Debug .. && make benchmark -j4
  - cd ../
  - #mkdir Release
  - #cd Release
  - #cmake -DCMAKE_BUILD_TYPE=Release .. && make -j4
  - #cd ../

after_success:
  - cd Debug
  - ls CMakeFiles/benchmark.dir/test/
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  - lcov --remove coverage.info '*/inc/Eigen3/*' --output-file coverage.info # filter out system
  - lcov --list coverage.info #debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
